### ISSUE TITLE
👋 Saying Hello from NodeSchool

### ISSUE THREAD

**Issue by martinheidegger** [nodejs/education#10]
Hello Node.js/education.

My Name is Martin Heidegger. I have for a long time been involved in NodeSchool. 
Recently I wrote about [the missing hands at NodeSchool](https://medium.com/@leichtgewicht/the-missing-hands-at-nodeschool-8999a90d33d1) In one part of the article I define NodeSchool as:

> NodeSchool … A loosely organized, international github organization with only one goal: Make it easy to **learn node.js** together in a friendly environment.

As a result of that article I have had contact with @jpwesselink and a little with @llkats and I think that _**we should talk** (Don't you think so too?)_.

I would love to hear what the Node Education Advisory Group thinks about NodeSchool and if we can join forces properly? Would you like to have a small get-together (online) and talk about stuff & feelings as well?

best regards and cheers
Martin Heidegger

**Comment by hackygolucky** [comment]
@jpwesselink and I chatted about this over the weekend but I think I missed you @martinheidegger! Sending an email was on my list of todos after the conf, but I was still digging out. Will do today :)

**Comment by jpwesselink** [comment]
Hi @hackygolucky and @martinheidegger and @llkats! I'm on UTC-04.00. I'm available any day the next two weeks

**Comment by martinheidegger** [comment]
Oh! Yeah: I am in UTC+09.00. I would be available mostly as well.
