### ISSUE TITLE
We have a Job Task Analysis(JTA) workshop in the works!

### ISSUE THREAD

**Issue by hackygolucky** [nodejs/education#16]
The ​JTA ​workshop to establish domains/topics of the Node.js Certification exam​ is going to take place over the course of two days, December 3 and 4, following Node Interactive US in Austin, TX.  ​Expect those two days to go from 9am-5pm ​with snack and lunch breaks. **Bonus points if your employer is able to cover some portion of your travel or lodging.** If you would like to request travel assistance, do so in the application below(ex: two days' hotel to stay a little bit longer).

If you're available, please fill out [THIS APPLICATION](https://t.co/S9vcVV7F5Y)
​
Considerations for workshop participation include:
availability
- e-signed agreement returned(will be provided in a separate email)
- variety of experience levels in Node.js and curriculum writing
- potential for employer to cover travel/costs partially covered by already booked travel for attending NI US.

Once I have confirmed your acceptance into the workshop, I will give you the details for the recommended lodging and the workshop location.

Please watch for a separate Echosign email that provides you with the Node.js Certification member agreement for contributing to the development once the application acceptances have been sent​.

For more information about this entire process, check out the abbreviated [roadmap](https://github.com/nodejs/education/blob/master/ROADMAP.md#certification) and [issues](https://github.com/nodejs/education/issues?utf8=%E2%9C%93&q=label%3Acertification%20) for contributing to various parts of the development.

cc @nodejs/tsc @nodejs/ctc @nodejs/evangelism

**Comment by dgonzalez** [comment]
You mention the online workshops (as I cannot attend to this one partly, because it is in the past). Is there any info about it?

**Comment by hackygolucky** [comment]
The first workshop was not online, as mentioned in this issue description @dgonzalez . It was an in-person event following Node Interactive, because there is a ton of coordination of ideas diverging and converging that must be facilitated and agreed upon to get this stuff moving--and it was recommended by a few experienced folks that this would be the best way to kickstart that phase. 

I am currently typing up a vaguer description of the domains and subtopics, because the participants in the workshop did such a good job and went into such detail that it can't be released verbatim because it would potentially share information vital to the scoring of the exam. Update soon!

**Comment by dgonzalez** [comment]
Perfect! please keep me into the loop... I am very interested in this subject.

**Comment by hackygolucky** [comment]
Working on releasing the results of this in the next week on the Node.js Medium account as well as next steps as another issue here in nodejs/education!
