### ISSUE TITLE
Education group at Node Interactive North America

### ISSUE THREAD

**Issue by hackygolucky** [nodejs/education#17]
### Purpose

Education meeting at Node Interactive call for attendance and discussion

### Proposal

I'd love for those who will be at Node Interactive and would like to talk about Education initiatives to  focus on for 2017 to have the opportunity to do so. I'm going to be filing for time during [Collaboration Summit](https://github.com/nodejs/summit/issues/35) so that we have space allotted to dig in. This would be a great in-person session to get started in volunteering with the Education group!

### Focus

An [Education Community Manager](https://github.com/nodejs/TSC/issues/46), Tracy Hinds @hackygolucky, was hired this year for a number of tasks related to Node.js education, but one person does not a movement make! This is an awesome chance to give far more input, make friends with folks who have been learning and teaching Node.js(hey @nodeschool/organizers !), and figure out some ways we can help folks develop docs, [get certified](https://github.com/nodejs/education/issues/3), discover resources, and welcome new folks to learning the language.

If you'll be there, please comment below! It'd be awesome to see a combination of new and legacy faces at the table.

**Comment by bnb** [comment]
Will be there 👍
