### ISSUE TITLE
Proposing a distributed Node Together / iteration of that concept

### ISSUE THREAD

**Issue by bnb** [nodejs/education#2]
## **A bit of back-story:**

I've been in an EXTREMELY rural area for the last 9 years. This has 100% prevented me from being able to attend meetups, or really find anyone else who is passionately interested in advancing web design or development - let alone Node. There is very little community here for most things, let alone technology.
## **Leadup:**

So, given this experience with having absolutely no community to bounce off of or talk to, I've struggled to find a mentor or someone to learn JavaScript or Node.js with successfully. I've had a plethora of time to think about how this could be solved, not just for myself but also for people in similar situations who are trying to learn Node.js or JavaScript.
## **Idea:**

Node Together and NodeSchool have always seemed like ideal ways for me to learn - working with an actual person instead of a predetermined set of instructions. Being able to _ask a question_ and have it be evaluated and responded to, given whatever circumstance.

I would like to bring this experience online - not just give it to people who can make it to a meetup. 

My base idea is to have two groups: **mentors** and **learners**. Each mentor would be paired with a small subset of the overall group of learners - ideally, I'd say, there would be less than 5 learners per mentor. No matter how gimmick-y it is, this goes along with the concept of "small class sizes" that many schools use - more interaction and attention from the teacher. This would be the _most_ conducive to learners actually learning Node.

What would the content be? That is one thing I'm not sure of - would the same kind of content at Node Together work? Or would a long-term (define that yourself) plan be better, since there's not as limited of a time-frame.

Some other questions that I do think need to be addressed with this:
- How will Mentors be picked? How will they be validated?
- If a Mentor doesn't know something, they should be able to access someone who does, either by asking that person or pulling that person into the discussion.
- Would we be able to pull Foundation members (corporate)
- How would learners be selected? Queue? All are added? Other ideas?
- Some kind of recognition of both Mentors

I'd absolutely LOVE any feedback and ideas from the community!

**Comment by rvagg** [comment]
Perhaps just start by trying to pull together a distributed NodeSchool event and go from there. I can relate to this need as well fwiw, I have to drive 3 hours to Sydney to find anything remotely resembling a Node community—I've relied on the online world for almost all of my growth as a programmer and online community is something I'm deeply attached to.

I got to be involved in hack.summit this year and it was done exclusively through https://www.crowdcast.io/ (which itself runs on Node), that might be a good platform to use for a basic education event and it can scale pretty heavily too if needed. I take your point about having small groups of learners but I wonder how you'd organise breakouts like that.

**Comment by bnb** [comment]
@rvagg That looks like a pretty good service. What steps would be involved with pulling together a distributed NodeSchool. Would we want to brand it officially as a NodeTogether/Node Foundation/Node Education Distributed Event, via NodeSchool?

**Comment by hollomancer** [comment]
Operation Code has a large audience in more rural areas. We would be interested in being involved with an event like this!

**Comment by hackygolucky** [comment]
Something else @ag_dubs and the NodeTogether team are going to be experimenting with is NodeTogether teacher training. The purpose of this would be for new teachers to be brought into the mix(Ashley doesn't scale unless we can get a people duplicator :P ) and creating a really welcoming environment while obtaining the skills necessary to set them up for teaching success! That, in the long run, will at least potentially allow for more NodeTogethers to happen locally, though not online specifically.

**Comment by bnb** [comment]
@hackygolucky That said, those teachers could also be moved toward or trained for helping online in 1:few situations. @ashleygwilliams has done an incredible job with NodeTogether, and having her experience and help would be A+. I would also _imagine_ that online is **highly** accessible to underrepresented groups - more so than meetups in select large cities.

**Comment by hackygolucky** [comment]
Yeah, I completely agree that online makes learning highly accessible. I believe we had this discussion in a NodeTogether meeting when you'd brought it up @bnb , and it wasn't that people didn't agree--everyone as far as I recall loved it. It's just a matter of *when*. In terms of scope and stabilizing the org to grow it more, we aren't quite there yet. I'd recommend you being a champion of it when we've got a roadmap documented(which we should see sooner than later with the all-hands I'm trying to schedule).
