### ISSUE TITLE
Node.js Certified Developer: Next phase of certification development is Item Writing!

### ISSUE THREAD

**Issue by hackygolucky** [nodejs/education#25]
#### The next phase of the Node.js certification development is Item Writing!

The Item Writing development will be held as a series of online, distributed webinars and collaborative video sessions to allow for global contribution. There will be 30 item writers--one per question. A smaller subset of these folks will comprise the Item Writing Review Team(IWRT). This group, 12 people, will be responsible for reviewing items written, hone unsatisfactory items, and have consensus/leveling meetings with the other members of the IWRT to finalize the question set. We're aiming for item writers to not be able to view questions in progress outside of the domain to which they are working on, so that they can remain eligible to be certified if they wish to do so. The IWRT will more likely be exposed to enough questions that this will be difficult to allow. Please keep this in mind when offering to take on one of these volunteering roles.

[Full Node.js Certific Developer content topic list](https://github.com/nodejs/education/blob/master/certification.md#the-topics)

Time commitment: 
- 1.5 hour intro webinar to learn the format and how to write the question(s)--item writers & IWRT
- 2 to 5 hours independently writing and reviewing the question with Item Writing Review Team members--items writers & IWRT
- 5 to 6 1-hour online meetings to reach consensus, group review, and level items--IWRT only

If you're interested in writing an exam question, fill out our application form [HERE](https://goo.gl/forms/G3UMBfNgDxt1lIbz2). You will be notified if accepted as an item writer via email.

If you'd like to read more about our prior work for developing the certification for Node.js, read more [HERE](https://github.com/nodejs/education/blob/master/certification.md#nodejs-certified-developer) and  [HERE](https://nodejs.org/en/blog/announcements/nodejs-certified-developer-program/).

**Comment by sumn2u** [comment]
:+1:

**Comment by kevin2r** [comment]
Is determined which testing platform will be used? You are about to write the tests and that's awesome!! but where? also the format of the exam, is it going to be multiple choice? I hope not, multiple choice exams are easy to memorize and they get filtered over the internet, and that's the state of current IT certifications, you can get a test file with a ton of questions that are similar to the real exam, then take the real exam and pass without understanding of what's going on. An exam platform where you have to write code by hand and get some hidden unit tests passed would be ideal.

**Comment by hackygolucky** [comment]
@kevin2r The environment is going to be an online, proctored in-browser IDE with questions that are partially coded and test takers will code to complete. Unit tests provided in each question will be run to verify.

**Comment by hackygolucky** [comment]
Since we have recruited and are actively working in this phase, I am closing this issue.

**Comment by YerkoPalma** [comment]
Hi @hackygolucky :wave: 
Is there any schedule that I've been missing? I would like to know if there is any date planned to the exam to go live. Also there is any information about the cost?

Cheers.
