### ISSUE TITLE
Can I start a Nodejs meetup in my school?

### ISSUE THREAD

**Issue by flickz** [nodejs/education#31]
Hello, 
I'm Flickz, a Nigerian, in love with Nodejs and I think I'd like to start a Nodejs meetup in my school as we have other meetups based on different technologies but there is nothing like Nodejs meetups. Although like every other learners out there, I'm still digging out the core values and fundamental Nodejs knowledge everyday but I believe I'm capable of teaching this fundamentals and values even as I learn. Plus, I believe in my leadership ability to build a community around this amazing technology in here. What do you think?

**Comment by fforres** [comment]
That's awesome @flickz! Kudos!
You can always look into initiatives like https://nodeschool.io/, IMO the workshops help a lot into structuring an event, teaching and bringing together the community. 
It has worked really well for us at http://github.com/noders :)

Also: Maybe some of the folks at https://github.com/nodejs/evangelism can provide ideas.

**Comment by bnb** [comment]
Definitely suggest looking into https://nodeschool.io - you could start up a chapter and get source material pretty easily! 

Additionally, I've created a thread in the Community Committee to discuss building out a simple document to share meetup resources - we may be able to gather some more resources together for you to get going quickly ❤️

**Comment by flickz** [comment]
Oh thats awesome. Thanks guys
