### ISSUE TITLE
Meta: move this team to CommComm

### ISSUE THREAD

**Issue by nebrius** [nodejs/education#33]
This team is currently under the TSC as a team, and there has been a request at https://github.com/nodejs/community-committee/issues/46 to move this team under CommComm.

CommComm has come to the consensus that the move makes sense from our end, but we want to open an issue here for everyone else on the education team to comment.

Do you all want to move from the TSC to CommComm?

**Comment by hackygolucky** [comment]
SGTM  :P

**Comment by add1sun** [comment]
Looks like this was done under nodejs/community-committee#46, so that this issue can be closed now.

**Comment by bnb** [comment]
Thanks @add1sun - closing 👍
