### ISSUE TITLE
Node.js The Right Way is out of print

### ISSUE THREAD

**Issue by Yasaa** [nodejs/education#36]
I was stacking up all the books recommended in the certification.md file and found Node.js The Right Way to be out of print.
https://pragprog.com/book/jwnode/node-js-the-right-way
Please replace it with a book just as good and which covers the concepts of exam syllabus-the concepts you chose it for.
Also,I would like to know if theexam would be conducted at Pearson Vue test centers or we must install a desktop app which does it,thereby allowing us to take the exam from anywhere in the world.
Thank you

**Comment by OlivierAlbertini** [comment]
maybe https://pragprog.com/book/jwnode2/node-js-8-the-right-way, this is the new version.
