### ISSUE TITLE
ROADMAP.md: Resources for learning Node.js

### ISSUE THREAD

**Issue by vdeturckheim** [nodejs/education#4]
On the roadmap, there is a "Resources for learning Node.js" paragraph (in progress).

What kind of links will be listed there ?
- Will it be a digest of quality documentation found online ?
- Will it be a set of documentation created by the WG to provide material for preparing the certification (at different levels) ?
- Something else ?

**Comment by hackygolucky** [comment]
Good questions!

There are several challenges with this. First stage could very well be suggestions of current good resources. 

Long term, we need to have a better solution for discoverability of all these great resources in the node ecosystem to learn. Meaning it is def bigger than a GitHub repo. I've seen a number of projects try to tackle this to weird and usually dead-ending results. It definitely needs to be "living".

**Comment by hackygolucky** [comment]
@vdeturckheim @kristianjaeger 

Do y'all have any interest in building up some conversations about 
- resources we could have in this repo or where else they should live
- consider how this could be structured for people trying to learn as(Getting Started in Node.js)
  - new developers
  - developers coming from other languages
  - people writing tooling but maybe not using Node.js on a regular basis
  - IoT folks

There are some limited but good lists on nodejs.org. I think seeing what discussions the www and docs working groups have had would also be helpful.

I would recommend maybe starting a document where people can contribute to requirements and scope(Google doc might be a little more dynamic than a PR of markdown) and share with folks?

**Comment by kristianjaeger** [comment]
@hackygolucky Sounds interesting.  For myself, I mostly have a background in C# but am using node more these days so I can relate to the "developers coming from other languages" item.  I like the Google doc idea too.  Cheers.

**Comment by vdeturckheim** [comment]
@hackygolucky I totally agree here. A google doc seems to be a good starting point to design what `this` will look like.

Semi-related though I had: maybe with the [evangelism WG](https://github.com/nodejs/evangelism), we can design presentations and workshop to be used evangelism context too.

Just to pin it, we can take a look at the notes [learning ruby from other languages](https://www.ruby-lang.org/en/documentation/ruby-from-other-languages/)

**Comment by bnb** [comment]
> resources we could have in this repo or where else they should live

I think having them _developed_ in this repo and then _pushed_ to the Website would be best. That way, newcomers (any of those from the group you listed) would just be able to go to the website for learning and education resources. That's typically the most logical and normal thing to do - go to a software's website to learn about it.

> I would recommend maybe starting a document where people can contribute to requirements and scope

Google Docs are really awesome for collaborative writing. That said, most Node.js stuff (in my experience, at least) has been done through GitHub to great success - including collaborative writing. GitHub line comments work pretty well for this, and allow for discussion and growth in a way that will get a lot more engagement from _this_ community (again, in my experience) than a Google Doc would.

**Comment by bnb** [comment]
@vdeturckheim 👍 to pulling in @nodejs/evangelism - would be more than willing to help with this.

**Comment by kristianjaeger** [comment]
@bnb Great ideas.  What is the timeline for this?  Cheers.

**Comment by bnb** [comment]
@kristianjaeger We need to get input and feedback from the people who would be the ones getting summarized. Getting their feedback is crucial - need to get those wheels spinning.

Here's the issue: https://github.com/nodejs/evangelism/issues/241

**Comment by hackygolucky** [comment]
@bnb I meant to respond to this earlier. I try to consider tools other than GitHub for educational initiatives when appropriate because I've found a portion of the community lives in GitHub but I've gotten a long list of contacts very interested in helping, and only find out about efforts through Medium posts, news articles, email letters, etc. I've been gratefully overwhelmed by the number of people who want to help but don't participate here. 

One would argue that I should encourage them to work in this space. Code may not be the universal language for our educational initiatives(some assume here that would be Node.js), and I'd like to create a space where experts can help improve learning Node.js without having to be onboarded to GitHub.(I experienced the hurdles of this quite a bit while working with researchers, designers, and managers at my last job.)

Ultimately, I think where this work can be surfaced transparently is partially in GH(projects that make sense to be developed there) but a central source of what's happening and what's moving ahead might be better suited for, say, an education page on nodejs.org then cross-posted or backed up here in GH.

**Comment by williamkapke** [comment]
@hackygolucky maybe prod @mikeal for what the purpose of https://github.com/nodejs/foundation.nodejs.org was...?

**Comment by kristianjaeger** [comment]
Good morning.  Do you guys work with a Scrum / two week sprint with backlog for items?  I'm curious because it seems there has not been much traction on some of these initiatives like the certification.  Do you need help organizing the initiatives?  Thanks.

**Comment by bnb** [comment]
@hackygolucky Thanks for the feedback - I totally get where you're coming from. I am very much 👍 on that central source that you discussed. I like pushing things to the website, but it seems less like a place for open discussion - more one-way broadcasting than two-way discussion. Is that the actual intent?

It sounds like these efforts just need a place to live and communicate that's agnostic of a developer focus. That's very do-able, and I think it would make everything a lot more transparent and successful - I would be happy to help with the messaging on it, as well.

My recommendation is a Slack team. I would be happy to work with you on setting it up in the most effective way, to ensure that everything gets running smoothly and provide an open and easy medium to use.

There are other options, like a forum, but they offer a much higher barrier to entry than a Slack team does.

Regardless what is used, having an open medium for more widespread discussion is going to really enable the Education efforts to be a massive success. The medium we choose isn't really super important as long as it can be used as an effective communication tool to share ideas and build together.

**Comment by hackygolucky** [comment]
@kristianjaeger As mentioned in prior issues you've commented on regarding Certification development, the majority of the Certification work is now happening not on GitHub at the moment due to meetings/planning discussions, and those who have offered their time commitments are being emailed regarding that work with updates. There's also been blockers(yay project management) from the contract side and legal reviewing documents in order for that work to move ahead.

**Comment by kristianjaeger** [comment]
@hackygolucky Okay, thanks for the update.  I certainly don't mean to be a pest.  Best of luck.  Please let me know if I can assist.  FYI, there are other open source initiatives like freecodecamp that are interesting with respect to this also.

**Comment by vdeturckheim** [comment]
@bnb I love the slack initiative
@hackygolucky Thanks for the updates.
Maybe, without too much contract/legal issues we can start discuss the global directions of this resource part. 
Monitoring the content of https://github.com/nodejs/education/issues/11 could help us define what needs to be here.

**Comment by stephenhuh** [comment]
@hackygolucky i'd be happy to compile a list of NodeJS learning resources as well as contribute towards them as well. Would this be helpful? Maybe further down the road the foundation could generate its own "official" content

**Comment by hackygolucky** [comment]
That sounds awesome @stephenhuh! Feel free to PR this https://github.com/nodejs/education/blob/master/getting-started-learning-nodejs.md 

But if the resources cover far more, run with multiple docs. We can figure out how it can be split up later if it's large enough to need that deeper navigation(such as the README being a content directory)
