### ISSUE TITLE
Collab Summit Berlin work

### ISSUE THREAD

**Issue by add1sun** [nodejs/education#41]
Hi all, I'm new to Node and the community, but I'm going to be in Berlin for JSConf and figure that the [Node Collab Summit](https://github.com/nodejs/summit/issues/60) that is happening with it would be a good place for me to meet folks and really dive in more.

As I posted over there, I'd love to work on reviving this Education team. While I can start poking at issues here in the repo, I think the summit would be a great opportunity to kickstart some new work on this. If someone else will be attending and would be interested in leading up an Education Team session, I'd love to help with whatever support I can provide within the capacity of a total newbie. :-)

**Comment by bnb** [comment]
Definitely agree that the Summit would be a really good place to get started on some new work for this repo @add1sun!

I know that there are a few other initiatives currently happening (like the website redesign) that are also working in a somewhat similar space, and would probably be able to collaborate very closely on this at the Summit 😁

**Comment by hackygolucky** [comment]
It's a great place to meet people and get a feel for what's already happening and what isn't, so you can figure out if you'd like to kickstart something or help an existing group. Are there any particular topics you're interested in seeing shine in the Education group @add1sun?

**Comment by add1sun** [comment]
Thanks to both of you. In terms of this team, I'm very interested in creating community resources (or a list of resources) that can be kept up-to-date, a la https://github.com/nodejs/education/issues/4, especially in light of the coming certification program. This is something that my company is looking to do already, but I'd like to make that work part of a community effort so that we make sure we benefit the community, and don't step on anyone's toes in the process. @bnb thanks for mentioning the website work, because I hadn't thought to look there and I see there is an issue about creating Getting Started content (https://github.com/nodejs/website-redesign/issues/18). So that would definitely we a good place to start helping.

In addition to resources for learning, I'm also very curious about the idea of a distributed Node Together (https://github.com/nodejs/education/issues/2), which seems like it is now defunct for in person events(?). (On a related note, is Node Together anything like, overlapping, or replaced by Code + Learn work? I see that Node Together is listed as an initiative and Code + Learn Friendliness is a proposed one, but with no champion. Also, I can totally ask in another issue queue/thread if that is out of scope here.)

In terms of collaboration with other groups/initiatives, I've also seen a mentors initiative, though it looks like a team hasn't really formed yet (https://github.com/nodejs/mentorship/issues/12). It would be great to meet and chat with those folks (whoever they may be :-)) at the Summit as well. 

For some background, I'm the CEO of an online training company that specializes in Drupal, and we've done a lot of work through and with the Drupal community over the years (I used to be the doc lead many moons ago and my team has worked on the community Drupal 8 Guide, amongst many other tasks/roles). As we are getting interested in Node, I'm looking to find out the best way to help Node documentation and learning as well.

So, I guess all that is to say that perhaps instead of an Education topic at the summit, I can just meet folks in like-minded groups, and see where I can help out. Unless there are others that have specific Education initiatives they would like to kickstart, in which case I'm very willing to help get this team bootstrapped again.
