### ISSUE TITLE
Node certs missing from enterprise offering

### ISSUE THREAD

**Issue by naugtur** [nodejs/education#45]
Hi,

Not sure if this is where I should report this, so feel free to point me elsewhere.

In the page for Node.js certification there's a link to this page: https://training.linuxfoundation.org/solutions/corporate-solutions/ 
```
Certifying 5 or more individuals?
Get a Corporate Quote >
```

The dropdown in corporate-solutions page doesn't have the Node.js trainings listed. 

It's unclear if they're only available individually or this is just a missing item.

**Comment by mhdawson** [comment]
@brianwarner FYI

**Comment by brianwarner** [comment]
Thanks, I've forwarded this on to the certification folks.
