### ISSUE TITLE
Outreachy mentorship opportunity--would you like to teach someone to contribute to Node.js core?

### ISSUE THREAD

**Issue by hackygolucky** [nodejs/education#7]
### The Node.js Foundation is applying to participate in [Outreachy](https://wiki.gnome.org/Outreachy) for the 2017 cycle.

Outreachy provides a collaborative environment in which newcomers from underrepresented backgrounds can get help working on their first contributions and a focused opportunity for them to dedicate a full-time effort to learning and contributing to FOSS. The program also assists people with finding mentors to help them with their projects. By participating in the program, interns develop a good understanding of the power of FOSS and skills necessary to continue contributing to it.

We would love to help make this happen for the Node.js project and finding at least one mentor and member company to help pair with a mentee for 2017 to contribute to Node.js core. To do this, the Node.js project needs
1. mentor(s) who can contribute the weekly hours and are interested in growing their skills as a mentor(listening, patience, teaching)
2. sponsor organization(s) to help fund each mentee. Outreachy requires $6500 per mentee that goes directly to the mentee as a stipend and admin costs.
3. the contribution that would be good for a mentee to work on during their internship.

_To note:_
- There is an application process to be a mentee. That will be announced later. 
- For every sponsor org and mentor we accept, we will be able to accept one mentee.

**What we're looking for:**
Mentors for Outreachy for Node.js should be able to commit 5 hours a week on most weeks towards the mentorship from the beginning of the application process through the end of the internships. Having a co-mentor or a project team who can review contributions and point people in the right direction can help spread the load. However, it's the primary mentor's responsibility to guide the intern, connect the intern with other people who can help, and review and merge intern's contributions throughout the internship or ensure other project participants do that.

**If you like what you read here and would like to volunteer yourself as a possible mentor**, please comment here and make sure we have a way to reach out to you(does your GH profile have an email attached to it?) or reach out to tracyhinds@linuxfoundation.org
#### Relevant Contribution Requirement

All mentees are required to make a small contribution to the project they are applying to work on. As a mentor, you will need to help applicants identify a suitable first task and help them out with it during the application process. Many successful applicants complete multiple tasks during the application process - please encourage them and support them in doing so.
#### Defining a Project

We will need to define what we'd like the mentee(s) to contribute to. We will discuss with the mentee(s) the details of the work they'll be doing during the internship period. It is best if the accepted participants work as part of the team, starting with smaller tasks (i.e. bugs) and progressing over time to more complex tasks (i.e. features), with each task being suggested by you based on the current priorities of the team. So the mentee(s) just need to know what areas of the project they are likely to work on and a tentative timeline.

The project should consist of manageable and relevant tasks that can be incorporated into the project throughout the internship period. Stand-alone projects proposed by an applicant are not suitable at all for people who are not established contributors. Please try to avoid situations when participants work on features that are not yet designed or agreed-upon, have too many moving parts, and would only land in the main code-base after the internship is over as a best-case scenario. This rarely works out. Instead, look for agreed-upon manageable bugs and small features that have a shared theme and would allow the participant to feel the satisfaction of landing her changes throughout the internship.

[more info for potential mentors](https://wiki.gnome.org/Outreachy/Admin/InfoForMentors)

@nodejs/ctc @nodejs/evangelism 
### UPDATE 9/13/16

I am finalizing sponsor conversations this week at Node Interactive EU. Thanks to all who have offered mentor time. Please make sure I have your email(if I haven't chatted with you in some way already) and I'll be touching base as soon as the money logistics are locked in.
### UPDATE 9/28/16

Primary mentors have been confirmed, but we are still looking for offers of help as supplemental mentors as well as [project ideas for the mentee to work on](https://github.com/nodejs/CTC/issues/17).

**Comment by dshaw** [comment]
Hi! :wave: Looking forward to supporting this initiative with the @NodeSource team.

**Comment by thefourtheye** [comment]
Please count me in.

**Comment by TheAlphaNerd** [comment]
o/

**Comment by bnoordhuis** [comment]
What kind of time commitment is expected from mentors?  It's five hours a week but for how many weeks?

Also, what is the makeup of the mentee pool expected to be like?  The impression I got from other projects was that it was mostly folks from the USA.  That makes it much less interesting because of the timezone difference.

**Comment by fforres** [comment]
I'm in :)

**Comment by fforres** [comment]
Count me in, I'd love to help.

**Comment by Trott** [comment]
Would be delighted to.

**Comment by gko** [comment]
Would like to help 🤓

**Comment by gvilla23** [comment]
I want to help!

**Comment by Trott** [comment]
Not Outreachy, and not a Foundation or Node.js project initiative, but seems related and I'm trying to get the word out so I'm just going to leave this here: http://nodetodo.org/

**Comment by vishwasrao** [comment]
Hi, I would like to work as mentor and contribute to this.

**Comment by JustinBeckwith** [comment]
Greetings folks!  The node.js team at Google would like to help as well.

**Comment by psbyron3** [comment]
Sounds awesome. I'd love more information but I would like to help

**Comment by somsharan** [comment]
Count me in

**Comment by bnb** [comment]
![image](https://cloud.githubusercontent.com/assets/502396/18009292/8d4e4a1c-6b79-11e6-8625-1cd4a92d96e7.png)

**Comment by bnb** [comment]
![I am ready.](http://i.giphy.com/l2JIn1SiIWVm8iPUQ.gif)

**Comment by bnb** [comment]
Awesome - very much want to participate. 👍

**Comment by fforres** [comment]
Currently reaching out to some colleagues at groupon. 
Hopefully more folks can get onboard.

**Comment by compmks** [comment]
Count me in 👍

**Comment by DEspino-Specialized** [comment]
I'm kind of new with Node.js but I would like to know how could I help

**Comment by sarahsharp** [comment]
@bnoordhuis: The application period is one month, and the internship is three months. Outreachy actually gets more interns from Europe and India than the U.S.

**Comment by thefourtheye** [comment]
I have been talking to people about contributing to Node.js, in all the meetups. I am suggesting [good first contribution](https://github.com/nodejs/node/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+contribution%22) tag as the starting point. 

People have been reading the docs and if they don't understand something, they give up it seems. Any suggestions to deal with this?

Also, can we have a link to the side of every section in the docs, so that people can directly click and edit to submit improvements? Will it be worth doing?

**Comment by addaleax** [comment]
@thefourtheye Not sure how this relates to this specific project here, but have you seen https://github.com/nodejs/node/issues/7147?

**Comment by addaleax** [comment]
I can’t commit to a full mentorship but I’d definitely love to help where I can!

**Comment by sauban** [comment]
This is great, I am very much interested in participating.

**Comment by yasinaydin** [comment]
Count me in!
