### ISSUE TITLE
Will certification include commonly overlooked subjects like security and performance?

### ISSUE THREAD

**Issue by kristianjaeger** [nodejs/education#8]
Grazie!

**Comment by hackygolucky** [comment]
Very likely yes, @kristianjaeger. 

Did you throw your hat into the ring for participating in the working sessions for the Job Task Analysis regarding the certification development? These sorts of topics and insight you're bringing in the issues are what we'd love to see in the discussions that we'll be scheduling soon. I'm happy to make a list of things that we get asked in the GH repo as well as concerns that community members would love to make sure are included or considered, too.

**Comment by kristianjaeger** [comment]
@hackygolucky Thanks.  Sure, I would be willing to participate.  I'm fairly new to node.js but am enjoying using it so far.

**Comment by hackygolucky** [comment]
@kristianjaeger closing this but opened this https://github.com/nodejs/education/issues/11 in order to funnel all of these convos into one place!
